export const CLIENT_EVENTS = {
  SET_PSEUDO: "set_pseudo",
  JOIN_ROOM: "join_room",
  CREATE_ROOM: "create_room",
  START_GAME: "start_game",
  TABLE_ORDER_TAP: "table_order_tap",
  TABLE_ORDER_ADJUST: "table_order_adjust",
  TABLE_ORDER_CONFIRMED: "table_order_confirmed",
  TABLE_ORDER_BACK: "table_order_back",
  ROLE_CONFIRMED: "role_confirmed",
  PROPOSE_TEAM: "propose_team",
  CONFIDENCE_VOTE: "confidence_vote",
  CONFIDENCE_RESULT_CONFIRMED: "confidence_result_confirmed",
  MISSION_VOTE: "mission_vote",
  MISSION_RESULT_CONFIRMED: "mission_result_confirmed",
  END_GAME_CONFIRMED: "end_game_confirmed",
  REPLAY_CHOICE: "replay_choice",
  LEAVE_ROOM: "leave_room",
} as const;

export const SERVER_EVENTS = {
  ROOM_UPDATED: "room_updated",
  ROOM_JOINED: "room_updated",
  GAME_STARTED: "game_started",
  TABLE_ORDER_UPDATED: "table_order_updated",
  ROLE_ASSIGNED: "role_assigned",
  PROPOSAL_PHASE: "proposal_phase",
  ROUND_STARTED: "proposal_phase",
  TEAM_PROPOSED: "proposal_phase",
  CONFIDENCE_PHASE: "confidence_phase",
  CONFIDENCE_REVEALED: "confidence_revealed",
  CONFIDENCE_RESULT: "confidence_revealed",
  MISSION_PHASE: "mission_phase",
  MISSION_PROGRESS: "mission_progress",
  MISSION_REVEALED: "mission_revealed",
  MISSION_RESULT: "mission_revealed",
  GAME_OVER: "game_over",
  ROLES_REVEALED: "roles_revealed",
  PLAYER_AFK: "player_afk",
  PLAYER_LEFT: "room_updated",
  RESYNC: "resync",
  ERROR: "error",
} as const;
