export const CLIENT_EVENTS = {
  SET_PSEUDO: "set_pseudo",
  JOIN_ROOM: "join_room",
  CREATE_ROOM: "create_room",
  START_GAME: "start_game",
  TABLE_ORDER_TAP: "table_order_tap",
  TABLE_ORDER_ADJUST: "table_order_adjust",
  TABLE_ORDER_CONFIRMED: "table_order_confirmed",
  TABLE_ORDER_BACK: "table_order_back",
  ROLE_CONFIRMED: "role_confirmed",
  PROPOSE_TEAM: "propose_team",
  CONFIDENCE_VOTE: "confidence_vote",
  CONFIDENCE_RESULT_CONFIRMED: "confidence_result_confirmed",
  MISSION_VOTE: "mission_vote",
  MISSION_RESULT_CONFIRMED: "mission_result_confirmed",
  END_GAME_CONFIRMED: "end_game_confirmed",
  REPLAY_CHOICE: "replay_choice",
  LEAVE_ROOM: "leave_room",
  CHAT_SEND: "chat_send",
  REPORT: "report",
  INVITE_FRIEND: "invite_friend",
} as const;

export const SERVER_EVENTS = {
  /** Envoyé au seul socket qui vient de rejoindre : porte son `playerId`. */
  ROOM_JOINED: "room_joined",
  /** État public de la room, diffusé à tous (jamais d'identifiant secret). */
  ROOM_UPDATED: "room_updated",
  PLAYER_LEFT: "player_left",
  GAME_STARTED: "game_started",
  GAME_ABORTED: "game_aborted",
  TABLE_ORDER_UPDATED: "table_order_updated",
  ROLE_ASSIGNED: "role_assigned",
  PROPOSAL_PHASE: "proposal_phase",
  CONFIDENCE_PHASE: "confidence_phase",
  CONFIDENCE_REVEALED: "confidence_revealed",
  MISSION_PHASE: "mission_phase",
  MISSION_PROGRESS: "mission_progress",
  MISSION_REVEALED: "mission_revealed",
  GAME_OVER: "game_over",
  ROLES_REVEALED: "roles_revealed",
  PLAYER_AFK: "player_afk",
  RESYNC: "resync",
  CHAT_MESSAGE: "chat_message",
  CHAT_HISTORY: "chat_history",
  REPORT_RECEIVED: "report_received",
  FRIEND_REQUEST: "friend_request",
  FRIENDS_CHANGED: "friends_changed",
  FRIEND_PRESENCE: "friend_presence",
  ROOM_INVITE: "room_invite",
  ERROR: "error",
} as const;
